---

- name: Configure cron job for periodically updating the search index
  cron:
    name: machina-vanilla update-index
    minute: "*/10"
    user: "{{ django_user }}"
    job: "{{ django_path }}/update_index.sh"

- name: Configure cron job for periodically resetting the app
  cron:
    name: machina-vanilla reset
    hour: 1
    minute: 0
    user: "{{ django_user }}"
    job: "{{ django_path }}/reset.sh"
